SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `auth_group`;
DROP TABLE IF EXISTS `auth_group_permissions`;
DROP TABLE IF EXISTS `auth_permission`;
DROP TABLE IF EXISTS `auth_user`;
DROP TABLE IF EXISTS `auth_user_groups`;
DROP TABLE IF EXISTS `auth_user_user_permissions`;
DROP TABLE IF EXISTS `django_admin_log`;
DROP TABLE IF EXISTS `django_content_type`;
DROP TABLE IF EXISTS `django_migrations`;
DROP TABLE IF EXISTS `django_session`;
DROP TABLE IF EXISTS `django_truncate_model1`;
DROP TABLE IF EXISTS `django_truncate_model2`;
DROP TABLE IF EXISTS `website_apartment`;
DROP TABLE IF EXISTS `website_flat`;
