# Generated by Django 4.0.1 on 2022-02-08 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committeemember",
            name="blood_group",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="committeemember",
            name="emergency_contact_number",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="committeemember",
            name="family_members",
            field=models.IntegerField(default=1),
        ),
    ]
