# Generated by Django 4.0.1 on 2022-02-08 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_committeemember_blood_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="committeemember",
            name="added_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
