# Generated by Django 4.0.1 on 2022-02-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_committeemember_added_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committeemember",
            name="added_on",
            field=models.DateField(auto_now_add=True),
        ),
    ]
