# Generated by Django 4.0.1 on 2022-02-16 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_flat_apartment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartment",
            name="flat",
        ),
        migrations.AddField(
            model_name="flat",
            name="apartment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.apartment",
            ),
        ),
    ]
