# Generated by Django 4.0.1 on 2022-02-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_alter_committeemember_flat_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committeemember",
            name="flat_number",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
