# Generated by Django 4.0.1 on 2022-02-16 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_alter_committeemember_flat_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committeemember",
            name="flat_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.flat",
            ),
        ),
    ]
