# Generated by Django 4.0.1 on 2022-01-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committeemembers",
            name="flat_number",
            field=models.CharField(max_length=50),
        ),
    ]
