# Generated by Django 4.0.1 on 2022-01-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_committeemembers_flat_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommitteeMembers',
            new_name='CommitteeMember',
        ),
    ]
